/* Automatically generated by configure */
#ifndef GF_CONFIG_H
#define GF_CONFIG_H
#define GPAC_CONFIGURATION "--static-bin"
#define GF_STATIC static
#define GF_NOT_EXPORTED
#define GPAC_STATIC_BIN
#define GPAC_STATIC_BUILD
#define GPAC_HAS_MTIM_NSEC
#define GPAC_CONFIG_LINUX
#define GPAC_HAS_QJS
#define GPAC_HAS_POLL
#define GPAC_64_BITS
#define GPAC_HAS_STRLCPY
#define GPAC_HAS_SOCK_UN
#define GPAC_HAS_IFADDRS
#define GPAC_DISABLE_3D
#endif
